<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ADisplayDoctors.aspx.cs" Inherits="HospitalManagementSystem.ADisplayDoctors" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <center><b>
            <br />
            <br />
            <asp:Label ID="lblADisplayDoctors" runat="server" Text="Display Doctors" Font-Size="X-Large"></asp:Label></b>
            <br />
            <br />
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" DataSourceID="SqlDataSourceADisplayDoctors">
                <Columns>
                    <asp:BoundField DataField="DoctorName" HeaderText="DoctorName" SortExpression="DoctorName" />
                    <asp:BoundField DataField="DoctorSpecialization" HeaderText="DoctorSpecialization" SortExpression="DoctorSpecialization" />
                    <asp:BoundField DataField="ConculatancyFee" HeaderText="ConculatancyFee" SortExpression="ConculatancyFee" />
                    <asp:BoundField DataField="Contact" HeaderText="Contact" SortExpression="Contact" />
                    <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSourceADisplayDoctors" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
                DeleteCommand="DELETE FROM [DoctorInfo] WHERE [DoctorName] = @DoctorName" 
                SelectCommand="SELECT * FROM [DoctorInfo]" 
                UpdateCommand="UPDATE [DoctorInfo] SET [DoctorName] = @DoctorName, [DoctorSpecialization] = @DoctorSpecialization, [ConculatancyFee] = @ConculatancyFee, [Contact] = @Contact, [Email] = @Email WHERE [DoctorName] = @DoctorName">
                <DeleteParameters>
                    <asp:Parameter Name="Id" Type="Int32" />
                </DeleteParameters>
                <UpdateParameters>
                    <asp:Parameter Name="DoctorName" Type="String" />
                    <asp:Parameter Name="DoctorSpecialization" Type="String" />
                    <asp:Parameter Name="ConculatancyFee" Type="Int32" />
                    <asp:Parameter Name="Contact" Type="String" />
                    <asp:Parameter Name="Email" Type="String" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
            <br />
            <asp:Button ID="btnBack" runat="server" OnClick="btnBack_Click" Text="Back" />
            </center>
        <div>
        </div>
    </form>
</body>
</html>
